py-pyrsistent: updated to 0.18.1
0.18.1, 2022-01-14
 * Add universal wheels for MacOS, thanks @ntamas for this!
 * Add support for Python 3.10, thanks @hugovk for this!
 * Fix 236 compilation errors under Python 3.10.
 * Drop official support for Python 3.6 since it's EOL since 2021-12-23.
 * Fix 238, failing doc tests on Python 3.11, thanks @musicinmybrain for this!

0.18.0, 2021-06-28
 * Fix 209 Update freeze recurse into pyrsistent data structures and thaw to recurse into lists and dicts,
   NB! This is a backwards incompatible change! To keep the old behaviour pass `strict=False` to freeze and thaw.
 * Fix 226, stop using deprecated exception.message.
 * Fix 211, add union operator to persistent maps.
 * Fix 194, declare build dependencies through pyproject.toml.
 * Officially drop Python 3.5 support.
 * Fix 223, release wheels for all major platforms.
 * Fix 221, KeyError obscured by TypeError if key is a tuple.
 * Fix LICENSE file name spelling.
 * Fix 216, add abstractmethod decorator for CheckedType and ABCMeta for _CheckedTypeMeta.
 * Fix 228, rename example classes in tests to avoid name clashes with pytest.

0.17.3, 2020-09-13
 * Fix 208, release v0.17.3 with proper meta data requiring Python >= 3.5.

0.17.2 (yanked awaiting proper fix for Python 3 req), 2020-09-09
 * Same as 0.17.1 released with more recent version of setuptools to get proper meta data for in place.

0.17.1 (yanked for proper meta data), 2020-09-09
 * Restrict package to Python >= 3.5 to not break unpinned Python 2 dependencies.

0.17.0 (yanked for Python 2 compatibility), 2020-09-08
 * Remove Python 2 support code. This includes dropping some compatibility code and the dependency on
   six.
 * Fix 200, python 3 exception chaining. This is a minor backwards incompatibility, hence stepping
   to 0.17.0.