xentools411: adapt for pciutils 3.8
Untested because of

In file included from include/ipxe/uaccess.h:27,
                 from core/acpi.c:28:
./config/ioapi.h:17:10: fatal error: config/local/ioapi.h: No such file or directory
   17 | #include <config/local/ioapi.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~

on -current/amd64.