py-rope: updated to 0.21.0
Release 0.21.0

Syntax support

- Handle `global` keyword when extracting method
- context manager:
  - Implement extract refactoring for code containing `async with`
  - Fix parsing of nested `with` statement/context manager
- list/set/dict/generator comprehension scope issues:
  - Added scopes for comprehension expressions
  - Added support for checking scopes by offset
  - Fix renaming global var affects list comprehension
  - Reuse of variable in comprehensions confuses method extraction
  - Fix error `TypeError: 'PyDefinedObject' object is not subscriptable`
- f-string:
  - Fix inlining into f-string containing quote characters
- inline assignment/walrus operator:
  - Fix `AttributeError: '_ExpressionVisitor' object has no attribute 'defineds'`

Bug fixes

- Fix improper replacement when extracting attribute access expression with `similar=True`
- Fix improper replacement when extracting index access expression with `similar=True`

New feature

- Move read() to FileSystemCommands

Misc

- Setup all-contributors bot
- Blacken source code, rope now follows black code style
- Add Github Actions to enforce black code style
- Remove plain 'unittest' only runner