xml-security-c: Update to 2.0.2. Patch from maya.
Changes:

2.0.0:

Bug

    [SANTUARIO-496] - DSA verification crashes OpenSSL on invalid combinations of key content

2.0.1:

Bug

    [SANTUARIO-491] - Default KeyInfo resolver doesn't check for empty element content.

2.0.0:

Bug

    [SANTUARIO-382] - Unconditionally enable large file support
    [SANTUARIO-418] - Invalid acceptance of unpadded RSA signatures
    [SANTUARIO-435] - Automake misses the subdir-objects option
    [SANTUARIO-437] - Cannot compile as C++11
    [SANTUARIO-447] - XSECCryptoX509::loadX509PEM() can read past unterminated buffer
    [SANTUARIO-449] - TXFMOutputFile can try to close unopened stream
    [SANTUARIO-470] - dsig/DSIGReference.cpp:931: bad type ?
    [SANTUARIO-471] - Patch for C++11 compile failures
    [SANTUARIO-473] - Build failure using NSS
    [SANTUARIO-474] - Better overflow checking
    [SANTUARIO-479] - xml-security-cpp compilation errors

Improvement

    [SANTUARIO-460] - Support for OpenSSL 1.1
    [SANTUARIO-461] - Internal key store should be deleted on any CryptoAcquireContext() error
    [SANTUARIO-472] - Conditional inclusion of XMKS code in library
    [SANTUARIO-476] - Change default behavior for inferring attribute IDness by name