x11/modular-xorg-xwayland: Fix build on netbsd<10.
Needs _OPENBSD_SOURCE for reallocarray, from the days before it was
(unfortunately) added to POSIX.

Resolves:

===> Building for modular-xorg-xwayland-23.1.1nb1
ninja: Entering directory `output'
[1/433] Compiling C object dix/liblibxserver_dix.a.p/atom.c.o
FAILED: dix/liblibxserver_dix.a.p/atom.c.o
cc -Idix/liblibxserver_dix.a.p -Idix -I../dix -IXext -I../Xext -IXi -I../Xi -Icomposite -I../composite -Idamageext -I../damageext -Ifb -I../fb -Iglamor -I../glamor -Imi -I../mi -Imiext/damage -I../miext/damage -Imiext/sync -I../miext/sync -Idbe -I../dbe -Idri3 -I../dri3 -Iinclude -I../include -Ipresent -I../present -Irandr -I../randr -Irender -I../render -Ixfixes -I../xfixes -I/pkg/2024Q4/include -I/pkg/2024Q4/include/pixman-1 -I/pkg/2024Q4/include/freetype2 -I/pkg/2024Q4/include/libpng16 -I/pkg/2024Q4/include/libdrm -I/usr/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -DHAVE_DIX_CONFIG_H -fno-strict-aliasing -fvisibility=hidden -Wall -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -O2 -fPIC -D_POSIX_THREAD_SAFE_FUNCTIONS -D_REENTRANT -D_DEFAULT_SOURCE -D_BSD_SOURCE -DHAS_FCHOWN -DHAS_STICKY_DIR_BIT -MD -MQ dix/liblibxserver_dix.a.p/atom.c.o -MF dix/liblibxserver_dix.a.p/atom.c.o.d -o dix/liblibxserver_dix.a.p/atom.c.o -c ../dix/atom.c
../dix/atom.c: In function 'MakeAtom':
../dix/atom.c:120:21: error: implicit declaration of function 'reallocarray'; did you mean 'reallocarr'? [-Werror=implicit-function-declaration]
             table = reallocarray(nodeTable, tableLength, 2 * sizeof(NodePtr));
                     ^~~~~~~~~~~~
                     reallocarr