kio: update to 5.108.0
5.99
  DesktopExecParser: Fix parsing of TerminalApplication when it contains args
  KPropertiesDialog: Split single command entry box into separate exec and args
  Allow hiding permissions tab
  Port http to workerbase
  Worker template: fix install location
  kcms/webshortcuts: hide from System Settings' main navigation
5.100
  Add new base class for thumbnail plugins
  Fix string formatting in "Do you really want to delete it?" message
  [kdiroperator] Don't add actions to actioncollection when building without deprecated API
  Deprecate KDirOperator::actionCollection
  [kfilewidget] Don't remove mkdir action from the action collection
  Fix deprecation of virtual functions
  Deprecate KDirOperator::setView(QAbstractItemView *)
  [kcoredirlister] Deprecate setMimeExcludeFilter
  [kcoredirlister] Rename showingDotFiles to showHiddenFiles
  [kdiroperator] Rename setView to setViewMode
  [kcoredirlister] Deprecate itemsFilteredByMime
  [kdiroperator] Remove usage of itemsFilteredByMime
  [knewfilemenu] Decouple from KActionCollection
  KPropertiesDialog: Add tooltip for magic mime type, too
  kurlnavigatortest: add test for absolute path in relative path handling
  KUrlNavigator: fix handling absolute paths
  kurlnavigatortest: add test case for relative hidden directory
  Remove KCrash dependency on Android
  KFilePlacesModel: Move open files error on teardown to KIO
  Add a CMake option, off by default, to control ftpd and wsgidav usage
  Conditionally chow hidden folders in the location bar's dropdown menu
  fix dav overwrite
  don't disable tests
  Warning dialogs: Change button text from "Delete" to "Delete Permanently"
  AskUserActionInterface: add DeleteInsteadOfTrash deletion type
  WidgetsAskUserActionHandler: fix showing file name for single url
  Message box methods: add API using "action" terms instead of "Yes" & "No"
  Deprecate defaulting to "Yes" & "No" message box buttons
  Add messagebox: KIO worker for testing messageBox() calls from worker
  Remove service type definition for urifilter plugins
  DeleteOrTrashJob: it's included in KF 5.100
  [ioslaves/remote] Convert kded metadata to JSON
  Fix missing details in message dialogs from worker
  UserNotificationHandler: fix messagebox type mismatches
  [kdiroperator] Allow accessing actions without KActionCollection
  KDirOperator: use KIO::DeleteOrTrashJob
  Add DeleteOrTrashJob
  [kopenwithdialog] Handle absence of a mime comment gracefully
  Port Windows-only code away from deprecated KIO API
  KFileItemListProperties: Better respect ioworker metadata
  KIO HTTP: Store error string for deferred result
  KFilePlacesView: Show busy indicator while (un)mounting a device
  KFilePlacesModel: Change teardown action to indicate teardown in progress
  KFilePlacesModel: Add DeviceAccessibilityRole
  KFilePlacesItem: Allow passing roles for dataChanged
5.101
  kproxydlg.ui the web page https://konqueror.org does not have a FAQ section
  Remove default Search items from Places panel
  Ignore finished() from the timeoutSpecialCommand
  KCoreUrlNavigator: fix header include path, add backward-compat headers
  Deprecate SlaveBase in favour of WorkerBase
  Fix header install location for KFileFilter
  Wrap IdleSlave in visibility deprecation macros
  Introduce KFileFilter class to parse and store filters
  Deprecate ForwardingSlaveBase in favour of ForwardingWorkerBase
  Introduce a new ForwardingWorkerBase
  KUrlNavigatorPlacesSelector: Use protocol icon as fallback
  Deprecate KProtocolInfo::slaveHandlesNotify()
  KIO::createDefaultJobUiDelegate Add missing @since
  Deprecate TCPSlaveBase in favour of TCPWorkerBase
  KProtocolInfoTest: adapt check for zip protocol support to JSON metadata
  Deprecate left-over no-op method SimpleJob::storeSSLSessionFromJob(...)
  Deprecate ThumbCreator and its variants
  RenameDialog: all widgets should be parented to the dialog itself
  Add KProtocolManager::workerProtocol() to match new lingo
  Add Scheduler methods for workers on hold to match new lingo
  Add KProtocolInfo::maxWorkers()/maxWorkersPerHost() to match new lingo
  Emit deprecation warning for ioslave_defaults.h
  Rename http_slave_defaults.h to http_worker_defaults.h, following port
5.102
  [kprocessrunner] Don't specify which desktop the app should be launched on
  Fix crash when dealing with user notification dialog
  [WidgetsAskUserActionHandler] Add fallbacks for dialog parent windows
  [jobuidelegate] Set window when creating delegate
  kdiroperator: fix full file path not being stripped
  Fix integer overflow for large files in AccessManager
  Pre-select "Delete" in Delete Confirmation Dialog
  Make link against KWindowSystem private
  [KOpenWithDialog] Save search history in state config
  file_unix: Fix check for hidden NTFS files
  Use new nomenclature with socket name; use ".socket" suffix
  [previewjob] Deprecate overlayIconSize and overlayIconAlpha
  Replace KIO::SlaveConfig with KIO::WorkerConfig
  [kpropertiesdialog] Remove UI to set DBus startup type
  when inside a sandbox use different openwith behavior
  Don't install service desktop files for KCMs in KF6
  Don't install KonqPopupMenu service type file for KF6
5.103
  CommandLauncher: Emit error when command was not found
  Add KUrlNavigator::supportedSchemes, to replace customProtocols
  Add missing copyFromFile entries to http.json for webdav and webdavs
  Mark WorkerBase::needSubUrlData as deprecated
  [commandlauncherjob] Deprecate setIcon
  job_error: add missing space between sentences for one string
  Correct setDesktopName() docs regarding optionality of .desktop suffix
  Drop outdated docs for mailto kioslave
  Add deprecation warnings for KDirOperator::setView(KFile::FileView)
  Deprecate unused Scheduler::connect/disconnects methods
  Deprecate Slave::isConnected/setConnected
  Restore old behavior for KFileFilterCombo::setFilter
  KCoreDirListerCache: Remove unnecessary assert
  KFilePlacesView: Set transientParent on context menu
  KURISearchFilterEngine: Use DuckDuckGo as a default shortcut
  widgets/renamefiledialog: remove bulk rename number limit
5.104
  DeleteOrTrashJob: when trashing a file in trash:/ delete it instead
  Set bug report URL for Windows Shares KCM
  OpenFileManagerWindowJob: fix opening multiple instances under Wayland [KF5]
  Add missing URLs in KCMs for reporting bugs
  kshorturifilter: return directly if cmd is empty
  [kprocessrunner] Use aliased desktop file name for xdg-activation
5.105
  CommandLauncher: call emitResult() as soon as process has started
  Also handle copy_file_range failing with ENOENT
  widgets/renamefiledialog: set number limit again
5.106
  ApplicationLauncherJob: find mimetype before showing open with dialog
  KPropertiesDialog: Don't quote the path unnecessarily
  KEncodingFileDialog: Sort the list of encodings by name
  WidgetsAskUserActionHandler: make sure all dialogs are created in the main thread
  WidgetsAskUserActionHandler: create message dialog in the main thread
  file: make sure to cancel reading if the worker was aborted
  KFileItemActions: don't add service submenus that don't have active actions
  KCoreDirLister: AutoUpdate wasn't incremented when a new lister opened an already listed dir
  SlaveInterface: Set button icon for "Continue Loading"
  Set ExitType when running applications as transient systemd services
5.107
  Deprecate KIO::AccessManager and related classes
  Enable thumbnail caching if thumbnail directory is on an encrypted volume
  KdirLister: update symlink dir content on file removal
  Polish menu before creating platform window
5.108
  KUrlRequester: restore unnamed filter compatibility with Plasma file dialog
  Add KUrlRequester::nameFilters, deprecate KUrlRequester::filter
  KUrlRequester::setFilter: note special filter syntax, allow unnamed filters
  KCoreDirLister::nameFilter: revert to non-partial matching again
  filewidgets/kfilewidget: Select and focus filename after canceling overwrite
  [previewjob] Check whether thumbRootDevice is valid before access