syncthing: update to 1.18.0
Bugfixes:

    irreversible Local Additions after re-adding the same folder as Receive Only
    Scan due to watcher can not found local change while modify file to empty
    TypeError: Cannot read property ‘urAccepted’ of undefined
    Out-of-sync state of zero-byte files is not reflected on peers

Enhancements:

    Add rest endpoint(s) to dismiss pending folder/device invitations
    Accepting a receive encrypted folder share should prompt the user to input a password
    Database GC can block for a long time
    Ensure encryption to untrusted on new, trusted device on an existing folder
    Use defaults for missing fields on the config rest API
    Show discovery and listener status when not failed