cmake: fix build on NetBSD releases such as 9.0.
NetBSD stdio.h has a bug with visibility of functions, so we get errors:
 error: '::vscanf' has not been declared

Define the other macro that can reach these definitions.

Issue already fixed by joerg in NetBSD stdio.h r1.35.