vim-gtk3: Fix gtk3 build after gtk3 3.24.1 update
vim-gtk3 was affected by a problem similar to PR pkg/53688, and
the test failed to recognize gtk3 due `undefined reference to
`epoxy_has_glx'' when `checking for GTK - version >= 3.0.0' in the
configure phase because instead of linking to pkgsrc libepoxy it
linked against builtin libepoxy.  Despite that it successfully
built without gtk3 support but gvim failed at run time with
`E25: GUI cannot be used: Not enabled at compile time' error.

Sort x11 bl3 includes so instead of failing at run time it fails
at build time when linking vim.

Add a kludge to override `--x-libraries' and `--x-includes' passed
by x11.buildlink3.mk to avoid linking against builtin libepoxy and
fix gtk3 support.

Thanks to and discussed with <rhialto> and <morr>!