archivers/ruby-zip: update to 1.2.3
Update ruby-zip to 1.2.3, here is release note.

1.2.3 (2019-05-23)

* Allow tilde in zip entry names #391 (fixes regression in 1.2.2 from #376)
* Support frozen string literals in more files #390
* Require pathname explicitly #388 (fixes regression in 1.2.2 from #376)

Tooling / Documentation:

* CI updates #392, #394
  - Bump supported ruby versions and add 2.6
  - JRuby failures are no longer ignored (reverts #375 / part of #371)
* Add changelog entry that was missing for last release #387
* Comment cleanup #385

Since the GitHub release information for 1.2.2 is missing, I will also include
it here:

1.2.2 (2018-09-01)

NB: This release drops support for extracting symlinks, because there was no
clear way to support this securely. See #376 (comment) for details.

* Fix CVE-2018-1000544 #376 / #371
* Fix NoMethodError: undefined method `glob' #363
* Fix handling of stored files (i.e. files not using compression) with general
  purpose bit 3 set #358
* Fix close on StringIO-backed zip file #353
* Add Zip.force_entry_names_encoding option #340
* Update rubocop, apply auto-fixes, and fix regressions caused by said
  auto-fixes #332, #355
* Save temporary files to temporary directory (rather than current directory)
  #325

Tooling / Documentation:

* Turn off all terminal output in all tests #361
* Several CI updates #346, #347, #350, #352
* Several README improvements #345, #326, #321