py-anyio: updated to 3.6.2
3.6.2

- Pinned Trio to < 0.22 to avoid incompatibility with AnyIO's ``ExceptionGroup`` class
  causing ``AttributeError: 'NonBaseMultiError' object has no attribute '_exceptions'``
  (AnyIO 4 is unaffected)