libxml2: restrict _POSIX_C_SOURCE to Linux
Fix build breakage with FreeBSD, where some definitions were then hidden
by __BSD_VISIBLE not being defined, e.g.:

  CC       libxml2_la-nanohttp.lo
nanohttp.c:837:20: error: use of undeclared identifier 'PF_INET6'
        s = socket(PF_INET6, SOCK_STREAM, IPPROTO_TCP);
                   ^
nanohttp.c:842:20: error: use of undeclared identifier 'PF_INET'
        s = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
                   ^
2 errors generated.

(Tested on FreeBSD 14 and Fedora Linux 39.)